image:
  repository: registry.cn-hangzhou.aliyuncs.com/eggplant/k8s-image-replacer
  tag: latest

webhook:
  failurePolicy: Ignore

  objectSelector: { }

  namespaceSelector: { }

config:
  docker_registry: "docker.lycoris.ac.cn"
  replace_policy:
    quay.io: "quay.lycoris.ac.cn"
    gcr.io: "gcr.lycoris.ac.cn"
    k8s.gcr.io: "k8s-gcr.lycoris.ac.cn"
    ghcr.io: "ghcr.lycoris.ac.cn"
    cloudsmith: "cloudsmith.lycoris.ac.cn"
